SAP_MAT_SETUP/Controllers/LogisticController.cs
using SAP_MAT_SETUP.CustomAuthentication;
using SAP_MAT_SETUP.Database;
using SAP_MAT_SETUP.Models;
using SAP_MAT_SETUP.MultipleModels;
using SAP_MAT_SETUP.Users;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace SAP_MAT_SETUP.Controllers
{
    public class LogisticController : Controller
    {
        // GET: Logistic
        string errorMsg;

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult NGList()
        {
            var db = new TKC_MASTER_SAPEntities();
            var RegID = db.T_SAP_MAT_SETUP.Where(x => x.I_Status_LG == null).OrderByDescending(c => c.I_RegID).ToList();
            return View(RegID);
        }

        [CustomAuthorize(Roles = "LG")]
        public ActionResult Logistic(string Id, string MatN)
        {
            var db = new TKC_MASTER_SAPEntities();
            var list = db.T_SAPMAT_SELLING_TYPE_PACKAGE.Where(x => x.M_MatNo == MatN).FirstOrDefault();


            var Mat = db.T_SAP_MAT_SETUP.Where(x => x.I_RegID == Id).FirstOrDefault();

            Logistic tmp = new Logistic();
            tmp.I_RegID = Mat.I_RegID;
            tmp.M_Model = Mat.M_Model;
            tmp.M_Lineoff = Mat.M_Lineoff;
            tmp.M_MatNo = Mat.M_MatNo;
            tmp.M_MatDesc = Mat.M_MatDesc;
            tmp.L_BoxQty = Mat.L_BoxQty;

            /* tmp.OEM = list.OEM;
             tmp.Part_Center = list.Part_Center;
             tmp.Export = list.Export;
             tmp.ComExport = list.ComExport;*/

            var Shipto = db.T_SAPMAT_SELLING_PLANT1.Where(x => x.I_RegID == Id).OrderBy(x => x.Ship_To).ToList();
            List<ListDropDownMatG> proc = new List<ListDropDownMatG>();
            foreach (var item in Shipto.Distinct())
            {
                ListDropDownMatG iTmp = new ListDropDownMatG();
                iTmp.iKey = item.Ship_To;
                iTmp.iValue = item.Ship_To;
                proc.Add(iTmp);
            }
            ViewBag.Shipto = proc;

            T_SAPMAT_SELLING_TYPE_PACKAGE tt = new T_SAPMAT_SELLING_TYPE_PACKAGE();
            if (list == null)
            {
                /*tt.OEM = 0;*/
                tt.Part_Center = 0;
                tt.Export = 0;
                tt.ComExport = 0;
            }
            else
            {
                /*tmp.OEM = list.OEM;*/
                tmp.Part_Center = list.Part_Center;
                tmp.Export = list.Export;
                tmp.ComExport = list.ComExport;
            }



            var shipto = db.T_SAPMAT_SELLING_PLANT1.Where(x => x.I_RegID == Id).OrderBy(x => x.Plant).ToList();
            if (shipto != null)
            {
                ViewBag.lstLG = shipto;
            }



                return View(tmp);
        }

        [HttpPost]
        public JsonResult updateLogistic(T_SAP_MAT_SETUP model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var db = new TKC_MASTER_SAPEntities();
                    var Data = db.T_SAP_MAT_SETUP.Where(x => x.I_RegID == model.I_RegID).FirstOrDefault();

                    if (Data != null)
                    {
                        Data.L_BoxQty = model.L_BoxQty;
                        Data.I_Status_LG = "OK";
                        Data.LastUpdBy = User.Identity.Name;
                        Data.LastUpdDate = DateTime.Now;
                        if (Data.I_Approve_LG != null)
                        {
                            Data.I_Approve_LG = null;
                        }

                        Data.Mat_Exported = null;
                        Data.Mat_ExpBy = null;
                        Data.Mat_ExpDate = null;

                        Data.Mat_Exported = null;
                        Data.Mat_ExpBy = null;
                        Data.Mat_ExpDate = null;
                        Data.Mat_Revise = null;

                        var i = db.SaveChanges();
                        getLGOK(model.I_RegID);
                        getPartOK(model.I_RegID);
                    }
                    else
                    {
                        return Json(new { result = "no data !!", message = "request successfully" });
                    }
                }
                catch (Exception ex)
                {
                    return Json(new { result = "error", message = "request successfully" });
                }
            }
            else
            {
                return Json(new { result = "input data!!", message = "request successfully" });
            }
            return Json(new { result = "insert success !!", message = "request successfully" });
        }

        public void getPartOK(string TkcPart) //check status
        {
            var db = new TKC_MASTER_SAPEntities();
            var Customer = db.T_SAP_MAT_SETUP.Where(x => x.I_RegID == TkcPart)
                .FirstOrDefault();

            if (Customer.I_Status_MK == "OK")
            {
                if (Customer.I_Status_PC == "OK")
                {
                    if (Customer.I_Status_LG == "OK")
                    {
                        if (Customer.I_Status_CO == "OK")
                        {
                            Customer.I_Status = "OK";
                            db.SaveChanges();
                        }
                        else
                        {
                            Customer.I_Status = "NG";
                            db.SaveChanges();
                        }
                    }
                    else
                    {
                        Customer.I_Status = "NG";
                        db.SaveChanges();
                    }
                }
                else
                {
                    Customer.I_Status = "NG";
                    db.SaveChanges();
                }
            }
            else
            {
                Customer.I_Status = "NG";
                db.SaveChanges();
            }
        }

        [HttpPost]
        public JsonResult getCustName(string Customers)
        {
            var db = new TKC_MASTER_SAPEntities();
            var Customer = db.T_SAPMAT_Cust_MS.Where(x => x.CustCD == Customers)
                .FirstOrDefault();
            //.OrderBy(x => x.iValue)
            return Json(new { result = Customer.CustName, message = "request successfully" });
        }

        public JsonResult getShipToName(string M_MatNo)
        {
            TKC_MASTER_SAPEntities db = new TKC_MASTER_SAPEntities();
            var Shipto = db.V_Customer_Package.ToList();

            List<ListDropDown> Model = new List<ListDropDown>();
            foreach (var item in Shipto.Where(x => x.M_MatNo == M_MatNo).OrderBy(x => x.Cust_ID).Distinct())
            {
                ListDropDown iTmp = new ListDropDown();
                iTmp.iKey = item.Cust_ID + " " + item.CUST_NAME;
                iTmp.iValue = item.Cust_ID;
                Model.Add(iTmp);
            }
            ViewBag.Shipto = Model;

            return Json(new { result = ViewBag.Shipto, message = "request successfully" });
        }

        [HttpPost]
        public JsonResult updateMatBoxQty(T_SAP_MAT_SETUP model)
        {
            try
            {
                
                var db = new TKC_MASTER_SAPEntities();
                var user = new AuthenticationDB();
                TKC_MASTER_SAPEntities dbcontext = new TKC_MASTER_SAPEntities();
                T_SAP_MAT_SETUP lstinsert = new T_SAP_MAT_SETUP();

                var Upd = dbcontext.T_SAP_MAT_SETUP.Where(x => x.I_RegID == model.I_RegID).FirstOrDefault();
                var matNo = dbcontext.T_SAP_MAT_SETUP.Where(y => y.I_RegID == model.I_RegID).FirstOrDefault();

                if (Upd != null)
                {
                    //checking before save

                    Upd.L_BoxQty = model.L_BoxQty;
                    if(Upd.I_Approve_LG != null)
                    {
                        Upd.I_Approve_LG = null;
                    }
                    ////////////////reset Price Export//////////////////////
                    //if (Upd.Price_Revise == null)
                    //{
                    //    Upd.Price_Revise = 0;
                    //}
                    //if (Upd.Price_Exported == "1")
                    //{
                    //    Upd.Price_Exported = null;
                    //    Upd.Price_Revise += 1;
                    //}
                    //else
                    //{
                    //    Upd.Price_Revise = Upd.Price_Revise;
                    //}
                    //Upd.Price_ExpBy = null;
                    //Upd.Price_ExpDate = null;
                    ////////////////reset Mat Export//////////////////////
                    Upd.Mat_Exported = null;
                    Upd.Mat_ExpBy = null;
                    Upd.Mat_ExpDate = null;
                    //if (Upd.Mat_Revise == null)
                    //{
                    //    Upd.Mat_Revise = 0;
                    //}
                    //if (Upd.Mat_Exported == "1")
                    //{
                    //    Upd.Mat_Exported = null;
                    //    Upd.Mat_Revise += 1;
                    //}
                    //Upd.Mat_ExpBy = null;
                    //Upd.Mat_ExpDate = null;
                    ////////////////////////////////////



                    var getupdate = User.Identity.Name;
                    var getUserRole = user.Users.Where(x => x.Username == getupdate).FirstOrDefault();
                    var Save = new T_SAPMAT_REVISE_LOG();
                    Save.i_Reg_id = Upd.I_RegID;
                    Save.page = "Mat Master";
                    Save.RevNo = Upd.Price_Revise;

SAP_MAT_SETUP/Views/Logistic/AddPKSelling.cshtml
@model SAP_MAT_SETUP.Database.T_SAPMAT_SELLING_TYPE_PACKAGE

@{
    ViewBag.Title = "Add Customer Package";

    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "10: OEM",
        Value = "10"
    });
    listItems.Add(new SelectListItem
    {
        Text = "11: Part Center",
        Value = "11",
    });
    listItems.Add(new SelectListItem
    {
        Text = "20: Export",
        Value = "20",
    });
}

@Html.Hidden("insPKSelling", @Url.Action("insPKSelling", "Logistic"))
@Html.Hidden("ViewData", @Url.Action("PKSelling", "Logistic"))
@Html.Hidden("getShipToName", @Url.Action("getShipToName", "Logistic"))

<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Add Customer Package</h1>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Material No:</label>
                            <span>
                                @Html.DropDownList("M_MatNo",
                                          new SelectList(ViewBag.mat, "iValue", "iKey"), "Choose Material No",
                                                 new { @class = "form-control", @style = "float:right;", @required = true })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-10">
                            <label>OEM:</label>
                            <span>
                                @Html.EditorFor(model => model.OEM, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.OEM, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Part Center:</label>
                            <span>
                                @Html.EditorFor(model => model.Part_Center, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Part_Center, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-10">
                                <label>Export:</label>
                                <span>
                                    @Html.EditorFor(model => model.Export, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Export, "", new { @class = "text-danger" })
                                </span>
                            </div>
                            <div class="col-md-2"></div>
                        </div>
                    </div>
                </div>
        </div>
        <br />

         <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-2"></div>
                            <div class="col-md-10">
                                <label>Component Export:</label>
                                <span>
                                    @Html.EditorFor(model => model.ComExport, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ComExport, "", new { @class = "text-danger" })
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <br />

        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3">
                <button type="button" class="btn btn-success btn-lg" onclick="insPKSelling()">Save</button>
            </div>
        </div>

    </div>
</div>

<script>
    function insPKSelling() {
        var urlAction = $('#insPKSelling').val();
        var param = {
            M_MatNo: $("#M_MatNo").val(),
            OEM: $("#OEM").val(),
            Part_Center: $("#Part_Center").val(),
            Export: $("#Export").val(),
            ComExport: $("#ComExport").val(),
        };
        console.log(param);
        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: param,
            success: function (obj) {
                alert("Add Package Complete!!");
                var urlAction = $('#ViewData').val();
                window.location.href = urlAction;
            }
        });
    }

    @*$("#M_MatNo").change(function () {

        var urlAction = $('#getShipToName').val();
        var MatNo = $("#M_MatNo").val();

        console.log(MatNo);
        $.ajax({
            url: urlAction,
            type: "POST",
            data: {
                M_MatNo: MatNo
            },
            success: function (obj) {
                console.log(obj);
                $("#ShipTo_Name").html('');
                $("#ShipTo_Name").append('<option>Choose Ship To Name</option>');
                $.each(obj.result, function (i, obj) {

                    $("#ShipTo_Name").append('<option value="' + obj.iValue + '">' + obj.iKey + '</option>');
                });
            }
        });
    });*@
</script>

<style>
    h1 {
        text-align: center;
    }

    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }
</style>

SAP_MAT_SETUP/Views/Logistic/ApproveLG.cshtml
@model IEnumerable<SAP_MAT_SETUP.Database.T_SAP_MAT_SETUP>

@{
    ViewBag.Title = "Approve";
}

@Html.Hidden("ViewData", @Url.Action("Index", "Account"))
@Html.Hidden("updateApproveLG", @Url.Action("updateApproveLG", "Logistic"))

<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
<style>
    #approveMKtable td, #approveMKtable th {
        white-space: nowrap;
    }

    #approveCStable td, #approveCStable th {
        white-space: nowrap;
    }
</style>
@*<link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
*@

<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Approve</h1>
        <br />

        <div class="row">
            @if (User.IsInRole("LG"))
            {
                <table id="approveLGtable" class="display select table table-bordered table-hover table-striped" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="select_all" value="1" id="checkAll"></th>
                            <th>Material No.</th>
                            <th>Customer Part No.</th>
                            <th>Customer Part Name</th>
                            <th>Box Qty.</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td><input type="checkbox" class="checkBox" value="@item.I_RegID" /></td>
                                <td>@Html.DisplayFor(modelItem => item.M_MatNo)</td>
                                <td>@Html.DisplayFor(modelItem => item.C_CustPNo)</td>
                                <td>@Html.DisplayFor(modelItem => item.M_CustPName)</td>
                                <td>@Html.DisplayFor(modelItem => item.L_BoxQty)</td>
                                @*<td>@Html.DisplayFor(modelItem => item.I_RegID)</td>*@
                            </tr>
                        }
                    </tbody>
                </table>
                <br />
                <div class="col-md-10"></div>
                <div class="col-md-2">
                    <button class="btn btn-success" id="btnLG" onclick="updateApproveLG()">Approve</button>
                </div>
            }

        </div>

    </div>
</div>

<script>

    var param = [];
    $(document).ready(function () {

        $("#checkAll").click(function () {
            $(".checkBox").prop('checked',
                $(this).prop('checked'));
        });

        $("#delete").click(function () {
            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/home/delete";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
            };
            options.error = function () {
                alert("Error while deleting the records!");
            };
            $.ajax(options);

        });

        $('#btnLG').click(function (e) {
            @*var param = [];*@
            $('input:checkbox:checked', '#approveLGtable').each(function () {
                //alert($(this).prop('value'));
                //param.push($(this).prop('value'));
                var objlist = {
                    iKey: $(this).prop('value'),
                    iValue: '',
                }
                param.push(objlist);
            });
            var urlAction = $('#updateApproveLG').val();
            var check = confirm("Are you sure!");
            if (check === true) {
                $.ajax({
                    url: urlAction,
                    type: "POST",
                    dataType: "JSON",
                    data: { listkey: param },
                    success: function (obj) {
                        console.log(param);
                        alert(obj.result);
                        var urlAction = $('#ViewData').val();
                        window.location.href = urlAction;
                    },
                    error: function (xhr, status, error) {
                        alert(xhr.responseText);
                    }
                });
            }

        });
    });

</script>

<style>
    h1 {
        text-align: center;
    }

    th {
        background: #D5D3D3;
        text-align: center;
    }

    th, td {
        border-color: #000;
    }

    approveMKtable {
        display: inline;
    }
</style>

SAP_MAT_SETUP/Views/Logistic/IMCT_PART_INPUT_QTY.cshtml
@*@model IEnumerable<SAP_MAT_SETUP.Database.T_IMCT_PART_INPUT_QTY>*@
@model dynamic

@{
    ViewBag.Title = "IMCT PART INPUT QTY";
}
@Html.Hidden("addInputQty", @Url.Action("addInputQty", "Logistic"))
@Html.Hidden("addInputQty2", @Url.Action("addInputQty2", "Logistic"))
@Html.Hidden("addInputQty3", @Url.Action("addInputQty3", "Logistic"))

<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
@*<script src="~/Scripts/popper.min.js"></script>*@
<style>
    #tbdisplay td, #tbdisplay th {
        white-space: nowrap;
    }

    .tooltip {
        position: relative;
        display: inline-block;
        border-bottom: 1px dotted black;
    }

        .tooltip .tooltiptext {
            visibility: hidden;
            width: 120px;
            background-color: black;
            color: #fff;
            text-align: center;
            border-radius: 6px;
            padding: 5px 0;
            /* Position the tooltip */
            position: absolute;
            z-index: 1;
            bottom: 100%;
            left: 50%;
            margin-left: -60px;
        }

        .tooltip:hover .tooltiptext {
            visibility: visible;
        }
</style>
<div class="card bg-light text-dark">
    <div class="card-body">
        <h1 style="text-align:center !important">INPUT QTY</h1>

        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="imct-tab" data-toggle="tab" href="#imct" role="tab" aria-controls="imct" aria-selected="true">IMCT PART</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="cust-tab" data-toggle="tab" href="#cust" role="tab" aria-controls="cust" aria-selected="false">CUST PART</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="path-tab" data-toggle="tab" href="#path" role="tab" aria-controls="path" aria-selected="false">GTOPAS IMG PATH</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="imct" role="tabpanel" aria-labelledby="imct-tab">
                <form class="form-inline my-2">
                    <input type="text" class="form-control" id="custpartNoTxt" placeholder="CustPart No">
                    <a role="button" class="btn btn-success" onclick="AddInputQty();" style="float:right">ADD</a>
                </form>

                <div class="table-responsive">
                    <table id="tbdisplay" class="table table-bordered table-hover table-striped wrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>CustPartNo</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model.t_IMCT_PART_INPUT_QTY)
                                {
                                    <tr>
                                        <td>
                                            @item.CustPartNo
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>

            </div>

            <div class="tab-pane fade" id="cust" role="tabpanel" aria-labelledby="cust-tab">
                <form class="form-inline my-2">
                    <input type="text" class="form-control" id="custIdTxt" placeholder="CustID">
                    <a role="button" class="btn btn-success" onclick="AddInputQty2();" style="float:right">ADD</a>
                </form>

                <div class="table-responsive">
                    <table id="tbdisplay2" class="table table-bordered table-hover table-striped wrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>CUSTID</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model.t_CustID_MS)
                                {
                                    <tr>
                                        <td>
                                            @item.CUSTID
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>

            </div>

            <div class="tab-pane fade" id="path" role="tabpanel" aria-labelledby="path-tab">
                <form class="form-inline my-2">
                    <input type="text" class="form-control" id="partNoTxt" placeholder="PartNumber">
                    <a role="button" class="btn btn-success" onclick="AddInputQty3();" style="float:right">ADD</a>
                </form>

                <div class="table-responsive">
                    <table id="tbdisplay3" class="table table-bordered table-hover table-striped wrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>PartNumber</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model.t_SPIS_PATH_GTOPAS)
                                {
                                    <tr>
                                        <td>
                                            @item.PartNumber
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>


    </div>
</div>
<script>

    function AddInputQty() {
        var custpartNoTxt = $('#custpartNoTxt').val();

        var urlAction = $('#addInputQty').val();
        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: {
                custpartNo: custpartNoTxt,
            },
            success: function (obj) {
                var result = obj.result

                if (result.includes("success"))
                    $('#tbdisplay').prepend('<tr><td>' + custIdTxt + '</td></tr>');

                alert(result);
            }
        });
    }

    function AddInputQty2() {
        var custIdTxt = $('#custIdTxt').val();

        var urlAction = $('#addInputQty2').val();
        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: {
                custId: custIdTxt,
            },
            success: function (obj) {
                var result = obj.result

                if (result.includes("success"))
                    $('#tbdisplay2').prepend('<tr><td>' + custIdTxt + '</td></tr>');

                alert(result);
            }
        });
    }

    function AddInputQty3() {
        var partNoTxt = $('#partNoTxt').val();

        var urlAction = $('#addInputQty3').val();
        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: {
                partNo: partNoTxt,
            },
            success: function (obj) {
                var result = obj.result

                if(result.includes("success"))
                    $('#tbdisplay3').prepend('<tr><td>' + partNoTxt + '</td></tr>');

                alert(result);
            }
        });
    }

    $(document).ready(function () {
        table = $('#tbdisplay').DataTable({
            "scrollX": true
        });

        table2 = $('#tbdisplay2').DataTable({
            "scrollX": true
        });

        table3 = $('#tbdisplay3').DataTable({
            "scrollX": true
        });
    });
</script>