SAP_MAT_SETUP/Models/Cust4MDSModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAP_MAT_SETUP.Models
{
    public class Cust4MDSModels
    {
        public string CustID { get; set; }
        public string DataType { get; set; }
        public string DataTypeRPT { get; set; }
        public string Sellingtype { get; set; }
    }
}

SAP_MAT_SETUP/Models/INPUT_QTY_MODEL.cs
using SAP_MAT_SETUP.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAP_MAT_SETUP.MultipleModels
{
    public class INPUT_QTY_MODEL
    {
        public List<T_IMCT_PART_INPUT_QTY> t_IMCT_PART_INPUT_QTY { get; set; }
        public List<T_CustID_MS> t_CustID_MS { get; set; }
        public List<T_SPIS_PATH_GTOPAS> t_SPIS_PATH_GTOPAS { get; set; }
        public INPUT_QTY_MODEL()
        {
            t_IMCT_PART_INPUT_QTY = new List<T_IMCT_PART_INPUT_QTY>();
            t_CustID_MS = new List<T_CustID_MS>();
            t_SPIS_PATH_GTOPAS = new List<T_SPIS_PATH_GTOPAS>();
        }
    }
}

SAP_MAT_SETUP/Models/LoginView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SAP_MAT_SETUP.Models
{
    public class LoginView
    {
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Required]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }
    }

    public class CustomSerializeModel
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public List<string> RoleName { get; set; }

    }

    public class RegistrationView
    {
        [Required(ErrorMessage = "User Name required")]
        [Display(Name ="User Name")]
        public string Username { get; set; }

        [Required(ErrorMessage = "First Name required")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name required")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Email required")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        public Guid ActivationCode { get; set; }

        [Required(ErrorMessage = "Password required")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Confirm Password required")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "Error : Confirm password does not match with password")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Department required")]
        [Display(Name = "Department")]
        public string Department { get; set; }



    }
}

SAP_MAT_SETUP/Models/Role_temp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAP_MAT_SETUP.Models
{
    public class Role_temp
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public virtual ICollection<SAP_MAT_SETUP.Users.Users> Users { get; set; }
    }
}

SAP_MAT_SETUP/Models/User_tmp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAP_MAT_SETUP.Models
{
    public class User_tmp
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public Guid ActivationCode { get; set; }
        public virtual ICollection<SAP_MAT_SETUP.Users.Roles> Roles { get; set; }

    }
}

SAP_MAT_SETUP/Controllers/SaleController.cs
using ClosedXML.Excel;
using SAP_MAT_SETUP.Database;
using SAP_MAT_SETUP.Models;
using SAP_MAT_SETUP.Users;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAP_MAT_SETUP.CustomAuthentication
{
   
    public class SaleController : Controller
    {
        // GET: Sale
        string _RegId, errorMsg;

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult DelMat(string id)
        {
            var db = new TKC_MASTER_SAPEntities();
            var items = db.T_SAP_MAT_SETUP.Where(x => x.I_RegID == id).FirstOrDefault();
            if (items != null)
            {
                db.T_SAP_MAT_SETUP.Remove(items);
                db.SaveChanges();
            }
            //ViewBag.plant = items;
            return Json(new { result = "Success !!", message = "request successfully" });
        }

        public ActionResult MTS()
        {
            TKC_MASTER_SAPEntities db = new TKC_MASTER_SAPEntities();

            var name = db.T_SAP_DATA_TO_SAP.ToList();
            List<ListDropDown> Name = new List<ListDropDown>();
            foreach (var item in name.Where(x => x.flag == 1).OrderBy(x => x.DATA_NAME).Distinct())
            {
                ListDropDown iTmp = new ListDropDown();
                iTmp.iKey = item.DATA_NAME;
                iTmp.iValue = item.DATA_SOURCE;
                Name.Add(iTmp);
            }
            ViewBag.name = Name;

            var model = db.T_SAP_MAT_SETUP.OrderBy(x => x.M_Model).ToList();
            List<ListDropDown> Model = new List<ListDropDown>();
            var disModel = model.Select(x => x.M_Model).Distinct().ToList();
            foreach (var item in disModel)
            {
                ListDropDown iTmp = new ListDropDown();
                iTmp.iKey = item;
                iTmp.iValue = item;
                Model.Add(iTmp);
            }
            ViewBag.model = Model;
            return View();
        }

        public async System.Threading.Tasks.Task<JsonResult> ExcelCM(string Model,string Datatype) //////////cust mat
        {
            var db = new TKC_MASTER_SAPEntities();
            var conn = db.Database.Connection;
            //var data = db.v_sap_mat_to_sap.ToList();
            var dt = new DataTable();
            var dtupd = new DataTable();
            var fileName = User.Identity.Name + "_CUSTOMER MATERIAL" + "_" + DateTime.Now.ToString("yyyyMMddHHmmss") + ".xlsx";

            try
            {
                await conn.OpenAsync();
                DbDataReader reader;

                var _Data = db.T_SAPMAT_SELLING_PLANT1.ToList(); //ใช้ foreach วนแล้วใช้ if เช็คว่า exported != 1 ,count_exp >=1

                //ใช้exported(dt)
                using (var command = conn.CreateCommand())
                {
                    string sql = "SELECT * FROM v_sap_cust_mat_to_sap WHERE Model = '" + Model + "' ORDER BY SoldTo , ShipTo , Material1 ASC";
                    command.CommandText = sql;
                    command.CommandTimeout = 0;
                    reader = await command.ExecuteReaderAsync();
                    dt.Load(reader);
                    reader.Close();
                }
                //ใช้update(dtupd)
                using (var command = conn.CreateCommand())
                {
                    string sql = "SELECT  * FROM v_sap_cust_mat_to_sap WHERE Model = '" + Model + "' and exported is null ";
                    command.CommandText = sql;
                    command.CommandTimeout = 0;

                    reader = await command.ExecuteReaderAsync();
                    dtupd.Load(reader);
                    reader.Close();
                }
                string fullPath = Path.Combine(Server.MapPath("~/temp"), fileName);
                FileStream file = new FileStream(fullPath, FileMode.Create, FileAccess.Write);
                try
                {
                    //Create column and inser rows
                    using (XLWorkbook wb = new XLWorkbook())
                    {
                        /* var ws = wb.Worksheets.Add(dt, "ALL");*/ //สร้าง worksheet
                        var SoldTo = dt.DefaultView.ToTable(true, "SoldTo");

                        //แยก Sheet ตาม SoldTo
                        foreach (DataRow item in SoldTo.Rows)
                        {
                            var result = dt.AsEnumerable();

                            DataTable dtResult = result.CopyToDataTable();

                            DataRow[] results = dt.Select("SoldTo = '" + item[0].ToString() + "'");
                            dtResult.Rows.Clear();
                            foreach (DataRow row in results)
                            {
                                dtResult.ImportRow(row);
                            }
                            if (dtResult.Rows.Count > 0)
                            {
                                var ws = wb.Worksheets.Add(dtResult, "SoldTo" + item[0].ToString());
                            }
                        }


                        /* var ws = wb.Worksheets.Add(dt, "ALL"); //สร้าง worksheet*/
                        /* ws = wb.Worksheets.Add("Sheet1");*/
                        Response.Clear();
                        Response.Buffer = true;
                        Response.Charset = "";
                        Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                        Response.AddHeader("Content-Disposition", "attachment;filename=\"" + fileName + "\"");

                        using (MemoryStream MyMemoryStream = new MemoryStream())
                        {
                            wb.SaveAs(MyMemoryStream);
                            MyMemoryStream.WriteTo(file);
                            file.Close();
                        }
                    }
                }
                catch (Exception e)
                {
                    return Json(new { fileName = "", errorMessage = "" });
                }

                if (dtupd.Rows.Count > 0)
                {
                    foreach (DataRow item in dtupd.Rows)
                    {
                        /*foreach (DataColumn col in dtupd.Columns)
                        {*/

                        string _id = item["I_RegID"].ToString();
                        string soldto = item["SoldTo"].ToString();
                        string shipto = item["ShipTo"].ToString();

                        var sapmatSellingPlant = (from c in db.T_SAPMAT_SELLING_PLANT1 where c.I_RegID == _id select c).ToList();
                        if (sapmatSellingPlant.Count > 0)
                        {
                            foreach (var data in sapmatSellingPlant)
                            {
                                data.Exported = "1";
                                data.ExpBy = User.Identity.Name;
                                data.ExpDate = DateTime.Now;
                            }

                            db.SaveChanges();
                        }

                        //updateSapmatSellingPlant(_id, db);
                        //var upd = db.T_SAPMAT_SELLING_PLANT1.Where(x => x.I_RegID == _id).FirstOrDefault();

                        //if (upd != null)
                        //{
                        //    upd.Exported = "1";
                        //    upd.ExpBy = User.Identity.Name;
                        //    upd.ExpDate = DateTime.Now;
                        //}

                        /* }*/
                        /* T_SAP_MAT_SETUP_LOG inslog = new T_SAP_MAT_SETUP_LOG();
                         inslog.UserId = User.Identity.Name;
                         inslog.FieldData = "Cust Mat";
                         inslog.Old = "";
                         inslog.New = Model;
                         inslog.UpDateTime = DateTime.Now.ToString();

                         db.T_SAP_MAT_SETUP_LOG.Add(inslog);
                         var j = db.SaveChanges();*/
                    }

                    //db.SaveChanges();
                }

                var user = new AuthenticationDB();
                var getupdate = User.Identity.Name;
                var getUserRole = user.Users.Where(x => x.Username == getupdate).FirstOrDefault();
                var Save = new T_SAPMAT_REVISE_LOG();
                Save.i_Reg_id = Model;
                Save.page = "Export " + Datatype;
                Save.RevNo = 0;
                Save.updDept = getUserRole.Roles.FirstOrDefault().RoleFullName.ToString();
                Save.updby = User.Identity.Name;
                Save.updDate = DateTime.Now;
                db.T_SAPMAT_REVISE_LOG.Add(Save);
                //upd.Count_Exp = upd.Count_Exp+1;//นับรอบในการexp
                var i = db.SaveChanges();
                return Json(new { isValid = true, fileName = fileName, result = "export data success !!", message = "export data success !!" });
            }
            catch (Exception ex)
            {
                errorMsg = ex.Message.ToString();
                return Json(new { isValid = false, fileName = "", result = "export data failed !!", message = errorMsg });
            }
            finally
            {
                conn.Close();
            }
            //return Json(new { fileName = fileName, errorMessage = "" });
        }
        public async System.Threading.Tasks.Task<JsonResult> ExcelMM(string Model,string Datatype) //////////mat master
        {
            var db = new TKC_MASTER_SAPEntities();
            var conn = db.Database.Connection;
            //var data = db.v_sap_mat_to_sap.ToList();
            var dt = new DataTable();

SAP_MAT_SETUP/Views/Sale/AddCFPricePack.cshtml
@model IEnumerable<SAP_MAT_SETUP.Database.T_SAP_Price_Package>

@{
    ViewBag.Title = "Add Confirm Price No/Package";
}

@Html.Hidden("insCFPricePack", @Url.Action("insCFPricePack", "Sale"))
@Html.Hidden("ViewData", @Url.Action("AddConfirm", "Sale"))

<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
<script src="~/Scripts/popper.min.js"></script>


<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Confirm Price No/Package</h1>
        <br />
        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3">
                <button type="button" class="btn btn-outline-primary" onclick="OpenPage()">Add Confirm Price No/Package</button>
            </div>
        </div>
        <br />
        <br />
        <div class="table-responsive">
            <table id="tbdisplay" class="table table-bordered table-hover table-striped wrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Confirm Price No/Package</th>
                        <th>Package Code</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Master_Price_Confirm_No</td>
                            <td>@item.Pk_CD</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<style>
    h1 {
        text-align: center;
    }

    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }
</style>
<script>

    function OpenPage() {

        var urlAction = $('#ViewData').val();
        window.location.href = urlAction;

    }

    $(document).ready(function () {
        $('#tbdisplay').DataTable();
    });
    function insCFPricePack() {
        var urlAction = $('#insCFPricePack').val();
        var param = {
            Master_Price_Confirm_No: $("#Master_Price_Confirm_No").val(),
            Pk_CD: $("#Master_Price_Confirm_No").val(),
        };
        console.log(param);
        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: param,
            success: function (obj) {
                alert("Add Confirm Price No/Package Complete!!");
                var urlAction = $('#ViewData').val();
                window.location.href = urlAction;
            }
        });
    }
</script>

SAP_MAT_SETUP/Views/Sale/AddConfirm.cshtml
@model SAP_MAT_SETUP.Database.T_SAP_Price_Package

@{
    ViewBag.Title = "Add Confirm Price No/Package";
}


@Html.Hidden("insCFPricePack", @Url.Action("insCFPricePack", "Sale"))
@Html.Hidden("ViewData", @Url.Action("AddCFPricePack", "Sale"))


<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Add Confirm Price No/Package</h1>
        <br />

        <div class="row">
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Confirm Price No/Package:</label>
                            <span>

                                @Html.EditorFor(model => model.Master_Price_Confirm_No, new { htmlAttributes = new { @class = "form-control", @maxlength = "15", @required = true } })
                                @Html.ValidationMessageFor(model => model.Master_Price_Confirm_No, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">

                        <!--<div class="col-md-10">
                            <label>Package Code:</label>
                            <span>
                                @Html.EditorFor(model => model.Pk_CD, new { htmlAttributes = new { @class = "form-control", @maxlength = "7", @required = true } })
                                @Html.ValidationMessageFor(model => model.Pk_CD, "", new { @class = "text-danger" })
                            </span>-->
                        @*<div class="col-md-4"></div>*@
                        <!--<div class="col-md-12">
                                <label style="font-size:12px;">*** If Master Price Confirm No less 15 character please fill Package Code</label>
                            </div>

                        </div>-->
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3">
                <button type="submit" class="btn btn-success" onclick="insCFPricePack()">Add</button>
            </div>
        </div>

    </div>
</div>

<style>
    h1 {
        text-align: center;
    }

    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }
</style>
<script>
    function insCFPricePack() {
        var urlAction = $('#insCFPricePack').val();
        var param = {
            Master_Price_Confirm_No: $("#Master_Price_Confirm_No").val(),
            Pk_CD: $("#Master_Price_Confirm_No").val(),
        };
        console.log(param);
        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: param,
            success: function (obj) {
                alert("Add Confirm Price No/Package Complete!!");
                var urlAction = $('#ViewData').val();
                window.location.href = urlAction;
            }
        });
    }
</script>

SAP_MAT_SETUP/Views/Sale/AddModel.cshtml
@model SAP_MAT_SETUP.Database.T_SAPMAT_Model

@{
    ViewBag.Title = "Add Model";
}

@Html.Hidden("insModel", @Url.Action("insModel", "Sale"))
@Html.Hidden("ViewData", @Url.Action("Model", "Sale"))

<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Add Model</h1>
        <br />

        <div class="row">
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Customer Code:</label>
                            <span>
                                @Html.DropDownList("CustCD",
                                          new SelectList(ViewBag.cust, "iValue", "iKey"), "Choose Customer",
                                                 new { @class = "form-control", @style = "float:right;", @required = true })
                                @Html.ValidationMessageFor(model => model.CustCD, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>Model:</label>
                            <span>
                                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-10"></div>
            <div class="col-md-2">
                <button type="button" class="btn btn-success" onclick="insModel()">Add</button>
            </div>
        </div>

    </div>
</div>

<style>
    h1 {
        text-align: center;
    }

    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }
</style>
<script>
    
    function insModel() {
        var urlAction = $('#insModel').val();

        var param = {
            Model: $("#Model").val(),
            CustCD: $("#CustCD").val(),
            
        };

        console.log(param);
        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: param,
            success: function (obj) {
                alert("Add Model Complete!!");
                var urlAction = $('#ViewData').val();
                window.location.href = urlAction;
            }
        });
    }
</script>

SAP_MAT_SETUP/Views/Sale/AddShipTo.cshtml
@model SAP_MAT_SETUP.Database.T_SAPMAT_PLANT

@{
    ViewBag.Title = "Add Ship To";
}

@Html.Hidden("insShipTo", @Url.Action("insShipTo", "Sale"))
@Html.Hidden("ViewData", @Url.Action("ShipTo", "Sale"))

<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Add ShipTo</h1>
        <br />

        <div class="row">
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Customer ID:</label>
                            <span>
                                @Html.EditorFor(model => model.CUSTID, new { htmlAttributes = new { @class = "form-control", @required = true, @maxlength = "4" } })
                                @Html.ValidationMessageFor(model => model.CUSTID, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>Customer Name:</label>
                            <span>
                                @Html.EditorFor(model => model.CUST_NAME, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                @Html.ValidationMessageFor(model => model.CUST_NAME, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Plant:</label>
                            <span>
                                @Html.EditorFor(model => model.PLANT, new { htmlAttributes = new { @class = "form-control", @required = true, @maxlength = "4" } })
                                @Html.ValidationMessageFor(model => model.PLANT, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>Sold To:</label>
                            <span>
                                @Html.EditorFor(model => model.SOLD_TO, new { htmlAttributes = new { @class = "form-control", @required = true, @maxlength = "7" } })
                                @Html.ValidationMessageFor(model => model.SOLD_TO, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Division:</label>
                            <span>
                                @Html.EditorFor(model => model.DIVISION, new { htmlAttributes = new { @class = "form-control", @required = true, @maxlength = "2" } })
                                @Html.ValidationMessageFor(model => model.DIVISION, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>Channel:</label>
                            <span>
                                @Html.EditorFor(model => model.CHANNEL, new { htmlAttributes = new { @class = "form-control", @required = true, @maxlength = "2" } })
                                @Html.ValidationMessageFor(model => model.CHANNEL, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Ship To:</label>
                            <span>
                                @Html.EditorFor(model => model.SHIP_TO, new { htmlAttributes = new { @class = "form-control", @required = true, @maxlength = "7" } })
                                @Html.ValidationMessageFor(model => model.SHIP_TO, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>Storage Location:</label>
                            <span>
                                @Html.EditorFor(model => model.Str_Loc, new { htmlAttributes = new { @class = "form-control", @required = true, @maxlength = "4" } })
                                @Html.ValidationMessageFor(model => model.Str_Loc, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-10"></div>
            <div class="col-md-2">
                <button type="button" class="btn btn-success btn-lg" onclick="insShipTo()">Add</button>
            </div>
        </div>

    </div>
</div>

<style>
    h1 {
        text-align: center;
    }

    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }
</style>
<script>

    function insShipTo() {
        var urlAction = $('#insShipTo').val();

        var param = {
            CUSTID: $("#CUSTID").val(),
            SOLD_TO: $("#SOLD_TO").val(),
            PLANT: $("#PLANT").val(),
            DIVISION: $("#DIVISION").val(),
            CHANNEL: $("#CHANNEL").val(),
            SHIP_TO: $("#SHIP_TO").val(),
            CUST_NAME: $("#CUST_NAME").val(),
            Str_Loc: $("#Str_Loc").val(),

        };

        console.log(param);
        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: param,
            success: function (obj) {
                alert("Add Ship To Complete!!");
                var urlAction = $('#ViewData').val();
                window.location.href = urlAction;
            }
        });
    }
</script>