SAP_MAT_SETUP/Controllers/CustomerController.cs
using SAP_MAT_SETUP.Database;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.Entity.Validation;
using System.IO;
using SAP_MAT_SETUP.Models;
using static SAP_MAT_SETUP.Controllers.HomeController;
using System.Data.SqlClient;

namespace SAP_MAT_SETUP.Controllers
{
    public class CustomerController : Controller
    {

        string connectionString = @"Data Source=tkcb01s;Initial Catalog=Sales;User ID=sa;Password=sa;Connection Timeout=5000;";
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SoldTo()
        {
            var db = new TKC_MASTER_SAPEntities();
            var Soldto = db.T_CUST_SOLD_TO.ToList();
            return View(Soldto);
        }

        public ActionResult Master()
        {
            /*var db = new TKC_MASTER_SAPEntities();
            var Soldto = db.T_CUST_SOLD_TO.ToList();*/
            return View();
        }

        public ActionResult EditSoldTo(string Id)//ดึง data ขึ้นมา show
        {
            var db = new TKC_MASTER_SAPEntities();
            int _Id = Convert.ToInt32(Id); //แปลง id เพราะมีค่าเป็น int
            var Soldto = db.T_CUST_SOLD_TO.Where(x => x.Id == _Id).FirstOrDefault();
            return View(Soldto);
        }

        public ActionResult AddSoldTo(string Id)//ดึง data ขึ้นมา show
        {
            var db = new TKC_MASTER_SAPEntities();
            var model = db.T_Division_Master.ToList();
            List<ListDropDown> List = new List<ListDropDown>();
            foreach (var item in model)
            {
                ListDropDown addlist = new ListDropDown();
                addlist.iKey = item.DivisionCD + " " + item.DivisionName;
                addlist.iValue = item.DivisionCD;
                List.Add(addlist);
            }
            ViewBag.List = List;
            return View();
        }

        public JsonResult insSoldTo(T_CUST_SOLD_TO model)
        {
            string msg = "";
            var db = new TKC_MASTER_SAPEntities();
            TKC_MASTER_SAPEntities dbcontext = new TKC_MASTER_SAPEntities();
            try
            {
                T_CUST_SOLD_TO insMat = new T_CUST_SOLD_TO();

                insMat.Id = '1';
                insMat.CustID_SOLD_TO = model.CustID_SOLD_TO;
                insMat.CustSAP_SOLD_TO = model.CustSAP_SOLD_TO;
                insMat.CustomerDesc = model.CustomerDesc;
                insMat.BranchCode = model.BranchCode;
                insMat.BranchDesc = model.BranchDesc;
                insMat.Channel = model.Channel;
                insMat.Division = model.Division;
                insMat.ExportCust = model.ExportCust;


                //model.Channel = "10"; สามารถfixedค่าได้
                dbcontext.T_CUST_SOLD_TO.Add(insMat);
                var i = dbcontext.SaveChanges();

                msg = "Success!!";

            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                msg = "error !!";
            }
            return Json(new { result = msg, message = "request successfully" });
        }

        public JsonResult DelSoldTo(int id)
        {
            var db = new TKC_MASTER_SAPEntities();
            var items = db.T_CUST_SOLD_TO.Where(x => x.Id == id).FirstOrDefault();
            if (items != null)
            {
                db.T_CUST_SOLD_TO.Remove(items);
                db.SaveChanges();
            }
            //ViewBag.plant = items;
            return Json(new { result = "Success !!", message = "request successfully" });
        }

        public JsonResult updateSoldto(T_CUST_SOLD_TO model) // update data ลง sql
        {
            try
            {
                var db = new TKC_MASTER_SAPEntities();
                var Data = db.T_CUST_SOLD_TO.Where(x => x.Id == model.Id).FirstOrDefault();

                if (Data != null)
                {
                    Data.CustID_SOLD_TO = model.CustID_SOLD_TO;
                    Data.CustSAP_SOLD_TO = model.CustSAP_SOLD_TO;
                    Data.CustomerDesc = model.CustomerDesc;
                    Data.BranchCode = model.BranchCode;
                    Data.BranchDesc = model.BranchDesc;
                    Data.Channel = model.Channel;
                    Data.Division = model.Division;
                    Data.ExportCust = model.ExportCust;

                    var i = db.SaveChanges();

                }
                else
                {
                    return Json(new { result = "no data !!", message = "request successfully" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = "error", message = "request successfully" });
            }

            return Json(new { result = "insert success !!", message = "request successfully" });
        }

        public ActionResult Cust4MDS()
        {
            List<Models.Cust4MDSModels> list = new List<Cust4MDSModels>();
            try
            {
                using (SqlConnection con = new SqlConnection())
                {
                    String sql = @"select * from T_SchCust4MDSOrders";
                    con.ConnectionString = @"Data Source=tkcb01s;Initial Catalog=Sales;User ID=sa;Password=sa;Connection Timeout=5000;";

                    DataTable dt = new DataTable();
                    SqlDataAdapter da = new SqlDataAdapter();
                    da.SelectCommand = new SqlCommand(sql, con);

                    da.Fill(dt);

                    foreach (DataRow row in dt.Rows)
                    {
                        var MDS = new Models.Cust4MDSModels();
                        MDS.CustID = row["CustID"].ToString();
                        MDS.DataType = row["DataType"].ToString();
                        MDS.DataTypeRPT = row["DataTypeRPT"].ToString();
                        MDS.Sellingtype = row["Sellingtype"].ToString();

                        list.Add(MDS);
                    }
                }
                return View(list);
            }
            catch
            {
                return View("Error");
            }

        }

        public ActionResult AddCust4MDS()//ดึง data ขึ้นมา show
        {
            return View();
        }
        [HttpPost]
        public JsonResult insCust4MDS(Cust4MDSModels model)
        {

            try
            {
                using (SqlConnection con = new SqlConnection(connectionString))
                {

                    con.Open();
                    string query = "Insert Into [Sales].[dbo].[T_SchCust4MDSOrders]([CustID],[DataType],[DataTypeRPT],[Sellingtype]) VALUES (@CustID,@DataType,@DataTypeRPT,@Sellingtype)";
                    SqlCommand cmd = new SqlCommand(query, con);
                    cmd.Parameters.AddWithValue("@CustID", model.CustID);
                    cmd.Parameters.AddWithValue("@DataType", model.DataType);
                    cmd.Parameters.AddWithValue("@DataTypeRPT", model.DataTypeRPT);
                    cmd.Parameters.AddWithValue("@Sellingtype", model.Sellingtype);
                    cmd.ExecuteNonQuery();
                }
                return Json(new { result = "success", message = "request successfully" });
            }
            catch (DbEntityValidationException e)
            {
                return Json(new { result = e, message = "request successfully" });
            }

        }

        [HttpPost]
        public JsonResult DelCust4MDS(string id)
        {
            try
            {
                var custid = id.Substring(0, 4);
                var dt = id.Substring(4, 2);
                var dt_rpt = id.Substring(6, 2);
                using (SqlConnection con = new SqlConnection(connectionString))
                {
                    con.Open();
                    string query = "Delete [Sales].[dbo].[T_SchCust4MDSOrders] where CustID = @CustID and DataType=@DataType and DataTypeRPT=@DataTypeRPT ";
                    SqlCommand cmd = new SqlCommand(query, con);
                    cmd.Parameters.AddWithValue("@CustID", custid);
                    cmd.Parameters.AddWithValue("@DataType", dt);
                    cmd.Parameters.AddWithValue("@DataTypeRPT", dt_rpt);
                    cmd.ExecuteNonQuery();

                    return Json(new { result = "Success", message = "request successfully" });
                }
            }
            catch (DbEntityValidationException e)
            {
                return Json(new { result = e, message = "request successfully" });
            }

        }

        public ActionResult ShipTo()
        {
            var db = new TKC_MASTER_SAPEntities();
            var Shipto = db.T_CUST_SHIP_TO_BY_CUSTID.ToList();
            return View(Shipto);
        }

        public ActionResult EditShipTo(string Id)
        {
            var db = new TKC_MASTER_SAPEntities();
            /*int _Id = Convert.ToInt32(Id);*/
            var Shipto = db.T_CUST_SHIP_TO_BY_CUSTID.Where(x => x.DockCode == Id).FirstOrDefault();
            return View(Shipto);
        }
        [HttpPost]
        public JsonResult DelShipTo(string Dockcode)
        {

SAP_MAT_SETUP/Views/Customer/AddCust4MDS.cshtml
@model SAP_MAT_SETUP.Models.Cust4MDSModels

@{
    ViewBag.Title = "Add Customer for MDS";
}
@Html.Hidden("insCust4MDS", @Url.Action("insCust4MDS", "Customer"))
@Html.Hidden("ViewData", @Url.Action("Cust4MDS", "Customer"))


<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Add Customer for MDS</h1>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Customer Id:</label>
                            <span>
                                @Html.EditorFor(model => model.CustID, new { htmlAttributes = new { @class = "form-control" , @maxlength = "4" } })
                                @Html.ValidationMessageFor(model => model.CustID, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>Data Type:</label>
                            <span>
                                @Html.EditorFor(model => model.DataType, new { htmlAttributes = new { @class = "form-control", @maxlength = "2" } })
                                @Html.ValidationMessageFor(model => model.DataType, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Data Type Report:</label>
                            <span>
                                @Html.EditorFor(model => model.DataTypeRPT, new { htmlAttributes = new { @class = "form-control", @maxlength = "2" } })
                                @Html.ValidationMessageFor(model => model.DataTypeRPT, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-10">
                            <label>Selling Type:</label>
                            <span>
                                @Html.EditorFor(model => model.Sellingtype, new { htmlAttributes = new { @class = "form-control", @maxlength = "1" } })
                                @Html.ValidationMessageFor(model => model.Sellingtype, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />
    </div>

    <div class="row">
        <div class="col-md-10"></div>
        <div class="col-md-2">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add" class="btn btn-success btn-lg" onclick="insCust4MDS()" />
                </div>
            </div>
        </div>
    </div>
    <br />
</div>

<script>
    function insCust4MDS() {
        var urlAction = $('#insCust4MDS').val();

        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: {

                CustID: $('#CustID').val(),
                DataType: $('#DataType').val(),
                DataTypeRPT: $('#DataTypeRPT').val(),
                Sellingtype: $('#Sellingtype').val(),
            },
            success: function (obj) {
                console.log(obj);
                alert("Add Complete!!");
                var urlAction = $('#ViewData').val();
                window.location.href = urlAction;

            }
        });
    }
</script>

<style>
    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }

    h1 {
        text-align: center;
    }
</style>

SAP_MAT_SETUP/Views/Customer/AddMds.cshtml
@model SAP_MAT_SETUP.Database.T_UPLOAD_SO_TO_SAP

@{
    ViewBag.Title = "EditMds";
}

@Html.Hidden("insMds", @Url.Action("insMds", "Customer"))
@Html.Hidden("ViewData", @Url.Action("Mdstosap", "Customer"))



<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Edit MDS TO SAP</h1>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Customer Id:</label>
                            <span>
                                @Html.EditorFor(model => model.CUST_ID, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CUST_ID, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>DATA TYPE:</label>
                            <span>
                                @Html.EditorFor(model => model.DATATYPE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DATATYPE, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Customer Name Group:</label>
                            <span>
                                @Html.EditorFor(model => model.CUSTNAME_GROUP, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CUSTNAME_GROUP, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-10">
                            <label>Plant Code:</label>
                            <span>
                                @Html.EditorFor(model => model.PlantCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PlantCode, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Due Time:</label>
                            <span>
                                @Html.EditorFor(model => model.DueTime, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DueTime, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>Type:</label>
                            <span>
                                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Remark1:</label>
                            <span>
                                @Html.EditorFor(model => model.Rem1, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Rem1, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>Remark2:</label>
                            <span>
                                @Html.EditorFor(model => model.Rem2, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Rem2, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />

    </div>
    <div class="row">
        <div class="col-md-10"></div>
        <div class="col-md-2">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add" class="btn btn-success btn-lg" onclick="insMds()" />
                </div>
            </div>
        </div>
    </div>
    <br />

</div>

<script>
    function insMds() {
        var urlAction = $('#insMds').val();

        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: {
               
                CUST_ID: $('#CUST_ID').val(),
                DATATYPE: $('#DATATYPE').val(),
                CUSTNAME_GROUP: $('#CUSTNAME_GROUP').val(),
                PlantCode: $('#PlantCode').val(),
                DueTime: $('#DueTime').val(),
                Type: $('#Type').val(),
                Rem1: $('#Rem1').val(),
                Rem2: $('#Rem2').val(),
            },
            success: function (obj) {
                console.log(obj);
                alert("Add Complete!!");
                var urlAction = $('#ViewData').val();
                window.location.href = urlAction;

            }
        });
    }
</script>

<style>
    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }

    h1 {
        text-align: center;
    }
</style>

SAP_MAT_SETUP/Views/Customer/Cust4MDS.cshtml
@model IEnumerable<SAP_MAT_SETUP.Models.Cust4MDSModels>

@{
    ViewBag.Title = "Customer for MDS";
}

@Html.Hidden("ViewData", @Url.Action("AddCust4MDS", "Customer"))
@Html.Hidden("DelCust4MDS", @Url.Action("DelCust4MDS", "Customer"))
@Html.Hidden("ViewData", @Url.Action("AddCust4MDS", "Customer"))

<script src="~/Scripts/jquery-3.5.1.js"></script>
<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>

@*<!DOCTYPE html>*@

<div class="card bg-light text-dark">
    <div class="card-body">
        <br />
        <h1>Customer for MDS</h1>
        <br />
        <div class="row">
            <div class="col-md-3">
                <button type="button" class="btn btn-primary" onclick="OpenPage()">Add Customer for MDS</button>
            </div>
            <div class="col-md-8"></div>

        </div>



        <h1></h1>
        <div class="table-responsive">
            <table id="tbdisplay" class="table table-bordered table-hover table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>Cust ID</th>
                        <th>DataType</th>
                        <th>DataType Report</th>
                        <th>Sellingtype</th>
                        <th>Delete</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.CustID)</td>
                            <td>@Html.DisplayFor(modelItem => item.DataType)</td>
                            <td>@Html.DisplayFor(modelItem => item.DataTypeRPT)</td>
                            <td>@Html.DisplayFor(modelItem => item.Sellingtype)</td>
                            <td><button type="button" class="btn btn-danger" id="btnDelete" value="@item.CustID@item.DataType@item.DataTypeRPT">DELETE</button></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        table = $('#tbdisplay').DataTable();

    });

    function OpenPage() {

        var urlAction = $('#ViewData').val();
        window.location.href = urlAction;
    }

    $('#tbdisplay').on("click", "button", function () {

        if (confirm('Do you want to delete this Customer list?')) {
            table.row($(this).parents('tr')).remove().draw(false);

            var id = $(this).val();
            console.log(id);

            var urlAction = $('#DelCust4MDS').val();
            $.ajax({
                url: urlAction,
                type: "POST",
                dataType: "JSON",
                data: {
                    id: id,

                },
                //success: function (obj) {
                //    //var urlAction = $('#DelShipTo').val();
                //    //$.ajax({
                //    //    url: urlAction,
                //    //    type: "POST",
                //    //    dataType: "JSON",
                //    //    data: {
                //    //        Dockcode: dockcode,

                //    //    },
                //    //success: function (obj) {

                //    //}
                //});
                //}
            });


        } else {

        }
    });
</script>

<style>
    h1 {
        text-align: center;
    }
</style>

SAP_MAT_SETUP/Views/Customer/EditMds.cshtml
@model SAP_MAT_SETUP.Database.T_UPLOAD_SO_TO_SAP

@{
    ViewBag.Title = "EditMds";
}

@Html.Hidden("updateMds", @Url.Action("updateMds", "Customer"))
@Html.Hidden("ViewData", @Url.Action("Mdstosap", "Customer"))
@Html.HiddenFor(model => model.Id)


<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Edit MDS TO SAP</h1>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Customer Id:</label>
                            <span>
                                @Html.EditorFor(model => model.CUST_ID, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CUST_ID, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-10">
                            <label>Data Type:</label>
                            <span>
                                @Html.EditorFor(model => model.DATATYPE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DATATYPE, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Customer Name Group:</label>
                            <span>
                                @Html.EditorFor(model => model.CUSTNAME_GROUP, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CUSTNAME_GROUP, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">

                        <div class="col-md-10">
                            <label>Plant Code:</label>
                            <span>
                                @Html.EditorFor(model => model.PlantCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PlantCode, "", new { @class = "text-danger" })
                            </span>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Due Time:</label>
                            <span>
                                @Html.EditorFor(model => model.DueTime, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DueTime, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />

    </div>
    <div class="row">
        <div class="col-md-10"></div>
        <div class="col-md-2">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-success btn-lg" onclick="updateMds()" />
                </div>
            </div>
        </div>
    </div>
    <br />

</div>

<script>
    function updateMds() {
        var urlAction = $('#updateMds').val();

        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: {
                Id: $('#Id').val(),
                CUST_ID: $('#CUST_ID').val(),
                DATATYPE: $('#DATATYPE').val(),
                CUSTNAME_GROUP: $('#CUSTNAME_GROUP').val(),
                PlantCode: $('#PlantCode').val(),
                DueTime: $('#DueTime').val(),

            },
            success: function (obj) {
                console.log(obj);
                alert("Update Complete!!");
                var urlAction = $('#ViewData').val();
                window.location.href = urlAction;

            }
        });
    }
</script>

<style>
    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }

    h1 {
        text-align: center;
    }
</style>