SAP_MAT_SETUP/Controllers/CostController.cs
using SAP_MAT_SETUP.CustomAuthentication;
using SAP_MAT_SETUP.Database;
using SAP_MAT_SETUP.Models;
using SAP_MAT_SETUP.Users;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace SAP_MAT_SETUP.Controllers
{
    public class CostController : Controller
    {
        // GET: Cost
        string errorMsg;

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult NGList()
        {
            var db = new TKC_MASTER_SAPEntities();
            var RegID = db.T_SAP_MAT_SETUP.Where(x => x.I_Status_CO == null).OrderByDescending(c => c.I_RegID).ToList();
            return View(RegID);
        }

        [CustomAuthorize(Roles = "CO,PU")]
        public ActionResult Costing(string Id)
        {
            var db = new TKC_MASTER_SAPEntities();
            var Mat = db.T_SAP_MAT_SETUP.Where(x => x.I_RegID == Id).FirstOrDefault();
            Costing tmp = new Costing();
            tmp.I_RegID = Mat.I_RegID;
            tmp.M_Model = Mat.M_Model;
            tmp.M_Lineoff = Mat.M_Lineoff;
            tmp.M_MatNo = Mat.M_MatNo;
            tmp.M_MatDesc = Mat.M_MatDesc;
            tmp.C_STD = Mat.C_STD;
            tmp.STD_Status = Mat.STD_Status;
            tmp.reson = Mat.flag01;

            return View(tmp);
        }

        [HttpPost]
        public JsonResult updateCosting(T_SAP_MAT_SETUP model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = new AuthenticationDB();
                    var db = new TKC_MASTER_SAPEntities();
                    var Data = db.T_SAP_MAT_SETUP.Where(x => x.I_RegID == model.I_RegID).FirstOrDefault();

                    if (Data != null)
                    {
                        Data.C_STD = model.C_STD;
                        Data.I_Status_CO = "OK";
                        Data.LastUpdBy = User.Identity.Name;
                        Data.LastUpdDate = DateTime.Now;
                        Data.STD_Status = model.STD_Status;
                        if (Data.I_Approve_CO != null)
                        {
                            Data.I_Approve_CO = null;
                        }
                        Data.flag01 = model.flag01;

                        ////////////////reset Price Export//////////////////////
                        //if (Data.Price_Revise == null)
                        //{
                        //    Data.Price_Revise = 0;
                        //}
                        //if (Data.Price_Exported == "1")
                        //{
                        //    Data.Price_Exported = null;
                        //    Data.Price_Revise += 1;
                        //}
                        //else {
                        //    Data.Price_Revise = Data.Price_Revise;
                        //}
                        //Data.Price_ExpBy = null;
                        //Data.Price_ExpDate = null;
                        ////////////////reset Mat Export//////////////////////
                        Data.Mat_Exported = null;
                        Data.Mat_ExpBy = null;
                        Data.Mat_ExpDate = null;
                        //if (Data.Mat_Revise == null)
                        //{
                        //    Data.Mat_Revise = 0;
                        //}
                        //if (Data.Mat_Exported == "1")
                        //{
                        //    Data.Mat_Exported = null;
                        //    Data.Mat_Revise += 1;
                        //}
                        //else
                        //{
                        //    Data.Mat_Revise = Data.Mat_Revise;
                        //}
                        //Data.Mat_ExpBy = null;
                        //Data.Mat_ExpDate = null;
                        ////////////////////////////////////

                        var getupdate = User.Identity.Name;
                        var getUserRole = user.Users.Where(x => x.Username == getupdate).FirstOrDefault();
                        var Save = new T_SAPMAT_REVISE_LOG();
                        Save.i_Reg_id = Data.I_RegID;
                        Save.page = "Mat Master";
                        Save.RevNo = Data.Price_Revise;
                        Save.updDept = getUserRole.Roles.FirstOrDefault().RoleFullName.ToString();
                        Save.updby = User.Identity.Name;
                        Save.updDate = DateTime.Now;
                        db.T_SAPMAT_REVISE_LOG.Add(Save);

                        var i = db.SaveChanges();
                        getCOOK(model.I_RegID);
                        getPartOK(model.I_RegID);
                        List<string> _Roles = new List<string> { "CO" };
                        var getemail = user.Users.Where(x => (x.Roles.Any(y => _Roles.Contains(y.RoleName)))).ToList();

                        foreach (var items in getemail)
                        {
                            string html = "<span style='font-family:Tahoma;font-size: 13pt;color:#1E90FF;'>";
                            html += "Dear  All concerns<br>";
                            html += "Cost have update in SAP Material System.<br>";
                            html += "I_RegID " + Data.I_RegID + "<br>";
                            html += "Model " + Data.M_Model + "<br>";
                            html += "Material number " + Data.M_MatNo + "<br>";
                            html += "Please check and prepare the information that related to you within due date.<br>";
                            html += "TKC <br>";
                            html += "System Development. <br>";
                            html += "Tel. 109";
                            html += "</span>";
                            NotificationEmail(items.Email, "SAP Material System have update", html);

                        }

                        //return Json(new { result = "insert success !!", message = "request successfully" });
                        return Json(new { isValid = true, result = "insert success !!", message = "request successfully" });

                    }
                    else
                    {
                        //return Json(new { result = "no data !!", message = "request successfully" });
                        return Json(new { isValid = false, result = "no data !!", message = "no data to send email !!" });
                    }
                }
                catch (Exception ex)
                {
                    //return Json(new { result = "error", message = "request successfully" });
                    errorMsg = ex.Message.ToString();
                    return Json(new { isValid = false, result = "error !!", message = errorMsg });

                }
            }
            else
            {
                //return Json(new { result = "input data !!", message = "request successfully" });
                //return Json("Error");
                return Json(new { isValid = false, result = "error !!", message = "input data!!" });
            }
            
        }

        public void getCOOK(string TkcPart) //check status
        {
            var db = new TKC_MASTER_SAPEntities();
            var Customer = db.T_SAP_MAT_SETUP.Where(x => x.I_RegID == TkcPart)
                .FirstOrDefault();

            if (Customer.CUSTOMER != null) // true
            {
                if (Customer.C_STD != null || Customer.flag01 != null)
                {
                    Customer.I_Status_CO = "OK";
                    db.SaveChanges();
                }
                else
                {
                    Customer.I_Status_CO = "NG";
                    db.SaveChanges();
                }
            }
            else
            {
                Customer.I_Status_CO = "NG";
                db.SaveChanges();
            }
        }

        public void getPartOK(string TkcPart) //check status
        {
            var db = new TKC_MASTER_SAPEntities();
            var Customer = db.T_SAP_MAT_SETUP.Where(x => x.I_RegID == TkcPart)
                .FirstOrDefault();

            if (Customer.I_Status_MK == "OK")
            {
                if (Customer.I_Status_PC == "OK")
                {
                    if (Customer.I_Status_LG == "OK")
                    {
                        if (Customer.I_Status_CO == "OK")
                        {
                            Customer.I_Status = "OK";
                            db.SaveChanges();
                        }
                        else
                        {
                            Customer.I_Status = "NG";
                            db.SaveChanges();
                        }
                    }
                    else
                    {
                        Customer.I_Status = "NG";
                        db.SaveChanges();
                    }
                }
                else
                {
                    Customer.I_Status = "NG";
                    db.SaveChanges();
                }
            }
            else
            {
                Customer.I_Status = "NG";
                db.SaveChanges();
            }
        }
        public void NotificationEmail(string email, string subject, string body)
        {

            System.Net.Mail.MailMessage msg = new System.Net.Mail.MailMessage();
            msg.From = new MailAddress("prones_g@tkoito.co.th");
            msg.To.Add(email);
            msg.Subject = subject;
            msg.Body = body;
            msg.IsBodyHtml = true;

            SmtpClient smtpClient = new SmtpClient();
            smtpClient.Port = 25;
            smtpClient.Host = "172.18.1.2";
            smtpClient.Credentials = new NetworkCredential("prones", "zaq1@wsx");
            smtpClient.Send(msg);
        }

SAP_MAT_SETUP/Views/PPC/AddRptGroup.cshtml
@model SAP_MAT_SETUP.Database.T_SAP_RPT_GROUP

@{
    ViewBag.Title = "Add Group Master Stock Report";
}

@Html.Hidden("insRptGroup", @Url.Action("insRptGroup", "PPC"))
@Html.Hidden("ViewData", @Url.Action("RptGroup", "PPC"))


<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Add Group Master Stock Report</h1>
        <br />

        <div class="row">
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Part No</label>
                            <span>

                                @Html.EditorFor(model => model.I_ITEM_CD, new { htmlAttributes = new { @class = "form-control", @maxlength = "15", @required = true } })
                                @Html.ValidationMessageFor(model => model.I_ITEM_CD, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Plant</label>
                            <span>

                                @Html.EditorFor(model => model.PLANT, new { htmlAttributes = new { @class = "form-control", @maxlength = "15", @required = true } })
                                @Html.ValidationMessageFor(model => model.PLANT, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Selling Type</label>
                            <span>

                                @Html.EditorFor(model => model.SELL_TYPE, new { htmlAttributes = new { @class = "form-control", @maxlength = "15", @required = true } })
                                @Html.ValidationMessageFor(model => model.SELL_TYPE, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Report Group</label>
                            <span>

                                @Html.EditorFor(model => model.RPT_GROUP, new { htmlAttributes = new { @class = "form-control", @maxlength = "40", @required = true } })
                                @Html.ValidationMessageFor(model => model.RPT_GROUP, "", new { @class = "text-danger" })
                            </span>
                            <div class="row">
                                <div class="col-md-4"></div>
                                <div class="col-md-8">
                                    <label style="color:red; font-size:14px">ไม่เกิน 40 ตัวอักษร</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <label>Add Month</label>
                            <span>

                                @Html.EditorFor(model => model.ADD_MNTH, new { htmlAttributes = new { @class = "form-control", @maxlength = "15", @required = true } })
                                @Html.ValidationMessageFor(model => model.ADD_MNTH, "", new { @class = "text-danger" })
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3">
                <button type="submit" class="btn btn-success btn-lg" onclick="insRptGroup()">Add</button>
            </div>
        </div>

    </div>
</div>

<style>
    h1 {
        text-align: center;
    }

    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }
</style>
<script>
    function insRptGroup() {
        var urlAction = $('#insRptGroup').val();
        var param = {
            I_ITEM_CD: $("#I_ITEM_CD").val(),
            PLANT: $("#PLANT").val(),
            SELL_TYPE: $("#SELL_TYPE").val(),
            RPT_GROUP: $("#RPT_GROUP").val(),
            ADD_MNTH: $("#ADD_MNTH").val(),
        };
        console.log(param);
        $.ajax({
            url: urlAction,
            type: "POST",
            dataType: "JSON",
            data: param,
            success: function (obj) {
                alert("Add RPT Group Complete!!");
                var urlAction = $('#ViewData').val();
                window.location.href = urlAction;
            }
        });
    }
</script>

SAP_MAT_SETUP/Views/PPC/ApprovePPC.cshtml
@model IEnumerable<SAP_MAT_SETUP.Database.T_SAP_MAT_SETUP>

@{
    ViewBag.Title = "Approve";
}

@Html.Hidden("ViewData", @Url.Action("Index", "Account"))
@Html.Hidden("updateApprovePPC", @Url.Action("updateApprovePPC", "PPC"))
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
<style>
    #approveMKtable td, #approveMKtable th {
        white-space: nowrap;
    }

    #approveCStable td, #approveCStable th {
        white-space: nowrap;
    }
</style>
@*<link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
*@

<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Approve</h1>
        <br />

        <div class="row">
            @if (User.IsInRole("PPC"))
            {
                <table id="approvePPCtable" class="display select table table-bordered table-hover table-striped" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="select_all" value="1" id="checkAll"></th>
                            <th>Material No.</th>
                            <th>Customer Part No.</th>
                            <th>Customer Part Name</th>
                            <th>Process</th>
                            <th>Spec</th>
                            <th>KB No.</th>
                            <th>Factory No.</th>
                            <th>Material Description</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td><input type="checkbox" class="checkBox" value="@item.I_RegID" /></td>
                                <td>@Html.DisplayFor(modelItem => item.M_MatNo)</td>
                                <td>@Html.DisplayFor(modelItem => item.C_CustPNo)</td>
                                <td>@Html.DisplayFor(modelItem => item.M_CustPName)</td>
                                <td>@Html.DisplayFor(modelItem => item.P_Process)</td>
                                <td>@Html.DisplayFor(modelItem => item.P_Spec)</td>
                                <td>@Html.DisplayFor(modelItem => item.P_KBNo)</td>
                                <td>@Html.DisplayFor(modelItem => item.P_FacNo)</td>
                                <td>@Html.DisplayFor(modelItem => item.M_MatDesc)</td>
                            </tr>
                        }
                    </tbody>
                </table>
                <br />
                <div class="col-md-10"></div>
                <div class="col-md-2">
                    <button class="btn btn-success" id="btnPPC" onclick="updateApprovePPC()">Approve</button>
                </div>
            }
        </div>

    </div>
</div>

<script>

    var param = [];
    $(document).ready(function () {

        $("#checkAll").click(function () {
            $(".checkBox").prop('checked',
                $(this).prop('checked'));
        });

        $("#delete").click(function () {
            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/home/delete";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
            };
            options.error = function () {
                alert("Error while deleting the records!");
            };
            $.ajax(options);

        });

        $('#btnPPC').click(function (e) {
            @*var param = [];*@
            $('input:checkbox:checked', '#approvePPCtable').each(function () {
                //alert($(this).prop('value'));
                //param.push($(this).prop('value'));
                var objlist = {
                    iKey: $(this).prop('value'),
                    iValue: '',
                }
                param.push(objlist);
            });
            var urlAction = $('#updateApprovePPC').val();
            $.ajax({
                url: urlAction,
                type: "POST",
                dataType: "JSON",
                data: { listkey: param },
                success: function (obj) {
                    console.log(param);
                    alert("Approve Complete!!");
                    var urlAction = $('#ViewData').val();
                    window.location.href = urlAction;
                },
                error: function (xhr, status, error) {
                    alert(xhr.responseText);
                }
            });
        });
    });
</script>

<style>
    h1 {
        text-align: center;
    }

    th {
        background: #D5D3D3;
        text-align: center;
    }

    th, td {
        border-color: #000;
    }

    approveMKtable {
        display: inline;
    }
</style>

SAP_MAT_SETUP/Views/PPC/NGList.cshtml
@model IEnumerable<SAP_MAT_SETUP.Database.T_SAP_MAT_SETUP>

@{
    ViewBag.Title = "NGList";
}


@Html.Hidden("ViewData", @Url.Action("NExport", "Sale "))
@Html.Hidden("ViewData1", @Url.Action("AddMarketing", "Home"))
@Html.Hidden("DelMat", @Url.Action("DelMat", "Account"))

@Html.Hidden("CopyMat", @Url.Action("CopyMat", "Home"))
@*<link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>*@
@*<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
*@

<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
@*<script src="~/Scripts/jquery-3.5.1.min.js"></script>*@
<script src="~/Scripts/popper.min.js"></script>
@*<script src="~/Scripts/bootstrap-4.5.2.min.js"></script>
    <script src="~/Scripts/jquery-3.5.1.js"></script>*@


<style>
    #tbdisplay td, #tbdisplay th {
        white-space: nowrap;
    }

    .tooltip {
        position: relative;
        display: inline-block;
        border-bottom: 1px dotted black;
    }

        .tooltip .tooltiptext {
            visibility: hidden;
            width: 120px;
            background-color: black;
            color: #fff;
            text-align: center;
            border-radius: 6px;
            padding: 5px 0;
            /* Position the tooltip */
            position: absolute;
            z-index: 1;
            bottom: 100%;
            left: 50%;
            margin-left: -60px;
        }

        .tooltip:hover .tooltiptext {
            visibility: visible;
        }
</style>

<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>MATERIAL MASTER SETUP</h1>

        <br />

        <div class="table-responsive">
            <table id="tbdisplay" class="table table-bordered table-hover table-striped wrap" style="width:100%">
                <thead>
                    <tr>
                        <th>RegID</th>
                        <th>Customer Part Name</th>
                        <th>Selling Type</th>
                        <th>Model</th>
                        <th>Lineoff</th>
                        <th>Material No.</th>
                        <th>Customer Part No.</th>
                        @if (User.IsInRole("PPC"))
                        {
                            <th> PPC </th>
                        }
                       
                        <th>View</th>
                        @if (User.IsInRole("MK,PPC,LG,CO,PU"))
                        {
                            <th>Edit</th>
                        }

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.I_RegID)</td>
                            <td>@Html.DisplayFor(modelItem => item.M_CustPName)</td>
                            <td>@Html.DisplayFor(modelItem => item.M_Remark)</td>
                            <td>@Html.DisplayFor(modelItem => item.M_Model)</td>
                            <td>@Html.DisplayFor(modelItem => item.M_Lineoff)</td>
                            <td>@Html.DisplayFor(modelItem => item.M_MatNo)</td>
                            <td style="text-align:left;">@Html.DisplayFor(modelItem => item.C_CustPNo)</td>
                            @*tab status*@
                            @if (User.IsInRole("PPC"))
                            {
                                if (item.I_Approve_PPC == null)
                                {
                                    <td style="color:#ff0000">NG</td>
                                }
                                else
                                {
                                    <td style="color: #329949" title="@item.I_Approve_PPC">OK</td>
                                }
                            }


                            <td>@Html.ActionLink("View", "ViewDetail", "Home", new { id = item.I_RegID }, null)</td>

                            @if (User.IsInRole("MK"))
                            {
                                <td>@Html.ActionLink("Edit", "EdtMar", "Home", new { id = item.I_RegID }, null)</td>
                            }
                            else if (User.IsInRole("PPC"))
                            {
                                <td>@Html.ActionLink("Edit", "Purchase", "PPC", new { id = item.I_RegID }, null)</td>
                            }
                            else if (User.IsInRole("LG"))
                            {
                                <td>@Html.ActionLink("Edit", "Logistic", "Logistic", new { id = item.I_RegID, Cust = item.C_CustPNo, CustN = item.CUSTOMER, MatN = item.M_MatNo }, new { target = "_blank" })</td>
                            }
                            else if (User.IsInRole("CO,PU"))
                            {
                                <td>@Html.ActionLink("Edit", "Costing", "Cost", new { id = item.I_RegID }, null)</td>
                            }


                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>

    function OpenPageIns(I_RegID) {
        @*console.log(I_RegID);*@
        @*alert(I_RegID);*@
        var urlAction = $('#ViewData1').val() +"?id="+ I_RegID;
        window.location.href = urlAction;
    }

    function OpenPage() {
        var urlAction = $('#ViewData').val();
        window.location.href = urlAction;
    }

    $(document).ready(function () {
        table = $('#tbdisplay').DataTable({
            "scrollX": true
        });

    });

    $('#tbdisplay').on("click", "button", function () {
        console.log('test');
        if (confirm('Do you want to delete this Material ?')) {
            table.row($(this).parents('tr')).remove().draw(false);

            var id = $(this).val();
            console.log(id);

            var urlAction = $('#DelMat').val();
            $.ajax({
                url: urlAction,
                type: "POST",
                dataType: "JSON",
                data: {
                    id: id,

                },
                success: function (obj) {

                }
            });
        } else {

        }
    });
</script>

<style>
    h1 {
        text-align: center;
    }

    th {
        background: #D5D3D3;
    }

    th, td {
        text-align: center;
    }
</style>

SAP_MAT_SETUP/Views/PPC/RptGroup.cshtml
@model IEnumerable<SAP_MAT_SETUP.Database.T_SAP_RPT_GROUP>

@{
    ViewBag.Title = "Group Master Stock Report";
}

@Html.Hidden("ViewData", @Url.Action("AddRptGroup", "PPC"))

<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
<script src="~/Scripts/popper.min.js"></script>

<div class="card bg-light text-dark">
    <div class="card-body">
        <h1>Group Master Stock Report</h1>
        <br />
        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3">
                <button type="button" class="btn btn-outline-primary" onclick="OpenPage()">Add RPT Group</button>
            </div>
        </div>
        <br />
        <br />
        <div class="table-responsive">
            <table id="tbdisplay" class="table table-bordered table-hover table-striped wrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Part No.</th>
                        <th>Plant</th>
                        <th>Selling Type</th>
                        <th>RPT Group</th>
                        <th>Add Month</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.I_ITEM_CD</td>
                            <td>@item.PLANT</td>
                            <td>@item.SELL_TYPE</td>
                            <td>@item.RPT_GROUP</td>
                            <td>@item.ADD_MNTH</td>
                            <td>@Html.ActionLink("Edit", "EditRptGroup", "Home", new { Item = item.I_ITEM_CD.ToString().Trim() }, null)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<style>
    h1 {
        text-align: center;
    }

    label {
        float: left;
    }

    span {
        display: block;
        overflow: hidden;
        padding: 0 4px 0 6px;
    }

    input {
        width: 100%;
        float: right;
    }
</style>
<script>

    function OpenPage() {

        var urlAction = $('#ViewData').val();
        window.location.href = urlAction;

    }

    $(document).ready(function () {
        $('#tbdisplay').DataTable();
    });

</script>